services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./data:/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
